export enum ActionType {
  GET_PRODUCTS='GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_ERROR='GET_PRODUCTS_ERROR',
  SET_COUNTER='SET_COUNTER',
  GET_DETAIL='GET_DETAIL',
  GET_DETAIL_SUCCESS='GET_DETAIL_SUCCESS',
  GET_DETAIL_ERROR='GET_DETAIL_ERROR',
  SEARCH_PRODUCT='SEARCH_PRODUCT',
  FILTER='FILTER'
}
